services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env   
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434/v1
      
    ports:
      - "8000:8000"

    #volumes:
      #- ./backend/test.db:/app/test.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
